# Generated by Django 4.2.30 on 2026-05-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playoffmatch',
            options={'ordering': ['created_at'], 'verbose_name': 'Match Phase Finale', 'verbose_name_plural': 'Matchs Phase Finale'},
        ),
        migrations.AlterField(
            model_name='playoffmatch',
            name='round_type',
            field=models.CharField(choices=[('quart_1_leg1', 'Quart de finale 1 - Aller'), ('quart_1_leg2', 'Quart de finale 1 - Retour'), ('quart_2_leg1', 'Quart de finale 2 - Aller'), ('quart_2_leg2', 'Quart de finale 2 - Retour'), ('quart_3_leg1', 'Quart de finale 3 - Aller'), ('quart_3_leg2', 'Quart de finale 3 - Retour'), ('quart_4_leg1', 'Quart de finale 4 - Aller'), ('quart_4_leg2', 'Quart de finale 4 - Retour'), ('semi_1_leg1', 'Demi-finale 1 - Aller'), ('semi_1_leg2', 'Demi-finale 1 - Retour'), ('semi_2_leg1', 'Demi-finale 2 - Aller'), ('semi_2_leg2', 'Demi-finale 2 - Retour'), ('third_place', 'Match 3ème place'), ('final', 'Finale')], max_length=20, verbose_name='Tour'),
        ),
    ]
